# Generated by Django 5.0.7 on 2024-09-03 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="El número debe estar en formato: '+507xxxxxxxx'.", regex='^\\+507\\d{8}$')]),
        ),
    ]
