# Generated by Django 5.0.7 on 2024-08-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
