# Generated by Django 5.0.7 on 2024-08-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services_images/'),
        ),
        migrations.DeleteModel(
            name='ServiceImage',
        ),
    ]
