# Generated by Django 5.0.7 on 2024-09-03 04:47

from django.db import migrations, connection

def remove_cart_tables(apps, schema_editor):
    with connection.cursor() as cursor:
        # Eliminar las tablas si existen
        cursor.execute("DROP TABLE IF EXISTS cart_cartitem;")
        cursor.execute("DROP TABLE IF EXISTS cart_cart;")
        
        # Eliminar las entradas de migración
        cursor.execute("DELETE FROM django_migrations WHERE app = 'cart';")


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_status'),
    ]

    operations = [
        migrations.RunPython(remove_cart_tables),
    ]
