# Generated by Django 5.0.7 on 2024-08-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_name_cart_status_cart_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
