# Generated by Django 5.0.7 on 2024-09-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_parent_category_alter_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='image_url',
        ),
    ]
