# Generated by Django 5.0.7 on 2024-09-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_image_productimage_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
