# Generated by Django 5.0.7 on 2024-09-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_image_url_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('DISPONIBLE', 'disponible'), ('AGOTADO', 'agotado'), ('PRÓXIMAMENTE', 'próximamente')], default='DISPONIBLE', max_length=20, null=True),
        ),
    ]
